package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	
}
