package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseUserOsc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOsc extends BaseUserOsc<UserOsc> {
	
}
