package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
}
